"""
Domain models for the Limit Order Book matching engine.

These are pure Python dataclasses — no ORM dependencies here.
The DB layer maps these to/from SQLAlchemy models separately.
"""

import uuid
from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from datetime import datetime, timezone


class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    LIMIT = "limit"
    MARKET = "market"


class OrderStatus(str, Enum):
    PENDING = "pending"     # Just created, not yet in book
    OPEN = "open"           # Resting in the order book
    PARTIAL = "partial"     # Partially filled, still resting
    FILLED = "filled"       # Fully executed
    CANCELLED = "cancelled" # Cancelled by user or system


@dataclass
class Order:
    """
    Represents a single order in the system.

    Immutable fields (set at creation): order_id, symbol, side, type, price, quantity, timestamp
    Mutable fields (updated during matching): remaining_quantity, filled_quantity, status
    """
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: Decimal
    price: Decimal  # For market orders, this is 0 / ignored

    order_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    client_order_id: str = ""  # Optional client-supplied ID

    # Mutable state
    remaining_quantity: Decimal = field(init=False)
    filled_quantity: Decimal = field(default=Decimal("0"))
    status: OrderStatus = field(default=OrderStatus.PENDING)

    def __post_init__(self):
        # Ensure Decimal types
        self.quantity = Decimal(str(self.quantity))
        self.price = Decimal(str(self.price))
        self.remaining_quantity = self.quantity
        self.filled_quantity = Decimal("0")

    def to_dict(self) -> dict:
        return {
            "order_id": self.order_id,
            "client_order_id": self.client_order_id,
            "symbol": self.symbol,
            "side": self.side.value,
            "order_type": self.order_type.value,
            "price": str(self.price),
            "quantity": str(self.quantity),
            "remaining_quantity": str(self.remaining_quantity),
            "filled_quantity": str(self.filled_quantity),
            "status": self.status.value,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class Trade:
    """
    Represents a single execution (fill) between two matched orders.
    Generated by the matching engine when orders cross.
    """
    trade_id: str
    symbol: str
    price: Decimal
    quantity: Decimal
    buy_order_id: str
    sell_order_id: str
    aggressor_side: OrderSide  # Which side initiated the trade
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def __post_init__(self):
        self.price = Decimal(str(self.price))
        self.quantity = Decimal(str(self.quantity))

    @property
    def notional_value(self) -> Decimal:
        """Total value of the trade (price × quantity)."""
        return self.price * self.quantity

    def to_dict(self) -> dict:
        return {
            "trade_id": self.trade_id,
            "symbol": self.symbol,
            "price": str(self.price),
            "quantity": str(self.quantity),
            "notional_value": str(self.notional_value),
            "buy_order_id": self.buy_order_id,
            "sell_order_id": self.sell_order_id,
            "aggressor_side": self.aggressor_side.value,
            "timestamp": self.timestamp.isoformat(),
        }
